# Initialize global constants
USERNAME_MAX_LEN = 15
CHAT_MSG_MAX_LEN = 100
DEFAULT_RATING = 1000
MIN_RATING = 1
MAX_RATING = 3000
PUBLIC_USER_ID = 0
DRAW_USER_ID = 0
DATABASE_FILE = "chesscorpy.db"
USER_SESSION = "user_id"
